# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: medigree.fhir.translations.langpack.pt
canonical: http://example.org/langpack
name: LangPackDemo
title: Language Pack Example
# description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Example Publisher
  # url: http://example.org/example-publisher
  # email: test@example.org


menu:
  Home: index.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true # true | false

parameters:
  i18n-default-lang: pt
  # i18n-lang: 
  #   - pt
  translation-supplements: input/translations/pt
  
